version: '3.8'

services:
  database:
    image: "postgres:16.1-alpine3.18" # imagem version
    restart: always
    env_file:
      - ../.env.development
    ports:
      - "5432:5432" # "host:container"
    # env_file:
    #   - .env
    # networks:
    #   - postgres-network
    # volumes:
    #   - ./db-data/:/var/lib/postgresql/data/
    #   - ./db-init/:/docker-entrypoint-initdb.d/

  # mailcatcher:
  #   ...
  # redis:
  #   ...